### ISSUE TITLE
pip install steganogan is throwing error

### ISSUE THREAD

**Issue by garimakaushik22** [DAI-Lab/SteganoGAN#24] opened 2019-01-08 16:33 UTC
I am using conda prompt with python version 3.6.5.  I ran pip command from anaconda prompt but it's throwing below error. 
Error:
(base) C:\Users\g.a.kaushik>pip install steganogan
Collecting steganogan
  Downloading https://files.pythonhosted.org/packages/7b/c6/51f9877b85b39d0c70ebf512f5afbafe089751f8e62f363381bbb12c1071/steganogan-0.1.1-py2.py3-none-any.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 2.2MB/s
Collecting torchvision==0.2.1 (from steganogan)
  Downloading https://files.pythonhosted.org/packages/ca/0d/f00b2885711e08bd71242ebe7b96561e6f6d01fdb4b9dcf4d37e2e13c5e1/torchvision-0.2.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 1.2MB/s
Collecting tqdm==4.28.1 (from steganogan)
  Downloading https://files.pythonhosted.org/packages/91/55/8cb23a97301b177e9c8e3226dba45bb454411de2cbd25746763267f226c2/tqdm-4.28.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting reedsolo>=0.3 (from steganogan)
  Downloading https://files.pythonhosted.org/packages/b7/fc/9a92265c7e8d556d3af1fc023727707385645fa05714bb25817448d6df76/reedsolo-0.3.tar.gz
Collecting scikit-learn==0.19.1 (from steganogan)
  Downloading https://files.pythonhosted.org/packages/67/e5/1459a3d6c6029a86b840b7701c48429d857eb2086916fec76f97c94dcc7a/scikit_learn-0.19.1-cp36-cp36m-win_amd64.whl (4.3MB)
    100% |████████████████████████████████| 4.4MB 604kB/s
Requirement already satisfied: scipy>=1.1.0 in c:\anaconda\lib\site-packages (from steganogan) (1.1.0)
Collecting imageio>=2.4.1 (from steganogan)
  Downloading https://files.pythonhosted.org/packages/28/b4/cbb592964dfd71a9de6a5b08f882fd334fb99ae09ddc82081dbb2f718c81/imageio-2.4.1.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 1.7MB/s
Collecting torch>=1.0.0 (from steganogan)
  Could not find a version that satisfies the requirement torch>=1.0.0 (from steganogan) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch>=1.0.0 (from steganogan)

**Comment by csala** [comment] 2019-01-09 09:14
Hello @garimakaushik22 Would you mind providing some more details about you environment?

Specifically, can you please fill the following form?

* SteganoGAN version or git commit:
* Python version (output of `pip --version`):
* Pip version (output of `pip --version`):
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste (all) the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

Regarding the error that you see, it looks like problem is not about installing SteganoGAN but about installing PyTorch.

Can you please try to install pytorch on its own to see if it works properly?
For this, please execute `pip install pytorch` and report the results, including the pytroch that was installed in case it works.

Also, bear in mind that conda does not always play well with standalone pip usage, so that might be the source of the error.
One possibility is that, even though you are using a python3.6 conda environment, your pip is running another python version from outside of your conda env.

So, if installing pytorch on its own does not work either, please have a look at some "using pip inside conda environment" resources and see if they help.

**Comment by csala** [comment] 2019-01-10 09:08
> As I can see conda is taking pip from anaconda package c:\anaconda\lib\site-packages\pip (python 3.6). Let me know if anything else needs to be checked here.

I believe the problem is there: this is not the right `pip`. As you can see, this is the "generic" pip binary, the one that is available system wide, when you should be using one that is specific to a conda env.

I'm sure there should be resources that explain how to setup `pip` properly to be used within a conda env. Can you check if they help?

Here you have an example: https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment
As you can see in the accepted answer, they end up installing `pip` and using it from a virtualenv (in this case named `venv_name`) instead of using the global one.

> I agree the problem is with PyTorch. But when I try to install PyTorch using pip, it throws error again.
I can research on installing PyTorch, but if we see from user perspective wouldn't this all be extra overhead on them? Can we improvise to include all this prerequisite in the code base itself, if that's possible.

I'm afraid not. If a user has problems installing SteganoGAN and asks for help here we will do our best to help them go over the issues, but setting up the environment to be able to use `pip` properly is something that they should be able to do on their own, definitely not within the scope of this project. At most, all we can do is provide some feedback and point them to the right resources to figure it out.

A part from that, including parts of third party tools within the code is not only a very bad practice that will lead to lots of problems in the long term, but also something that has no end. If PyTorch cannot be installed because `pip` is not setup properly, so may other libraries, and I'm sure that you will see where this could potentially lead to :-)

So, I think the only option here is setting up the environment so that PyTorch or any other dependencies can be installed using `pip` on the user side.

**Comment by garimakaushik22** [comment] 2019-01-16 09:54
Hi
I have installed pytorch and now I face issue with scikit-learn which  I have already installed  through pip command and it says requirement successful but when I run the  command to install steganogan, I get below error. 


 Rolling back uninstall of scikit-learn
Command "C:\Anaconda\envs\steg\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\GA07C1~1.KAU\\AppData\\Local\\Temp\\pip-install-vjkl_d8c\\scikit-learn\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\GA07C1~1.KAU\AppData\Local\Temp\pip-record-mzqghb3q\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GA07C1~1.KAU\AppData\Local\Temp\pip-install-vjkl_d8c\scikit-learn\

**Comment by csala** [comment] 2019-01-16 10:34
Hi @garimakaushik22 It's very difficult to see what the error is here.

Would you mind pasting the whole sequence of commands and their output, and formatting everything as code using markdown?
In order to do so, please surround the whole block of code using triple backticks:  ` ``` `

**Comment by garimakaushik22** [comment] 2019-02-15 08:36
Hi, 
I am getting below error after correcting all torch and scikit learn issue. I saw this is a known issue in torch. Please find the error. 
```
>>> steganogan.encode('C:\\Users\\g.a.kaushik\\SteganoGAN\\research\\input.png', 'C:\\Users\\g.a.kaushik\\SteganoGAN\\research\\output.png', 'This is a super secret message!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\steg\lib\site-packages\steganogan\models.py", line 304, in encode
    generated = self.encoder(cover, payload)[0].clamp(-1.0, 1.0)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\envs\steg\lib\site-packages\steganogan\encoders.py", line 62, in forward
    x = layer(torch.cat(x_list + [data], dim=1))
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: $ Torch: not enough memory: you tried to allocate 5GB. Buy new RAM! at ..\aten\src\TH\THGeneral.cpp:201
>>>

```

**Comment by pvk-developer** [comment] 2019-02-15 10:54
Hi @garimakaushik22 
I think that this may be VRAM issue. Could you try loading the model with `cuda=False`:
```
>>> steganogan = SteganoGAN.load(architecture='dense', cuda=False)
```
Or before running `steganogan.encode` you can run: `steganogan.set_device(cuda=False)`

Or if you would like to use it from the `command line interface` just use: `steganogan encode -i path_to_image -o path_to_output 'This is a secret message' --cpu`

**Comment by garimakaushik22** [comment] 2019-02-15 17:50
Hi,
I have tried both the above option still getting same error. 
```
>>> steganogan.set_device(cuda=False)
>>> steganogan.encode('C:\\Users\\g.a.kaushik\\SteganoGAN\\research\\input.png', 'C:\\Users\\g.a.kaushik\\SteganoGAN\\research\\output.png', 'This is a super secret message!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\steg\lib\site-packages\steganogan\models.py", line 304, in encode
    generated = self.encoder(cover, payload)[0].clamp(-1.0, 1.0)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\envs\steg\lib\site-packages\steganogan\encoders.py", line 62, in forward
    x = layer(torch.cat(x_list + [data], dim=1))
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Anaconda\envs\steg\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: $ Torch: not enough memory: you tried to allocate 3GB. Buy new RAM! at ..\aten\src\TH\THGeneral.cpp:201
>>>

```

**Comment by garimakaushik22** [comment] 2019-02-20 08:12
Hi,

I am also running on 8GB RAM.  I have tried running it with CUD= FALSE but still it shows RAM issue. Can you please suggest what is the RAM configuration  needed?

**Comment by csala** [comment] 2019-02-20 15:42
Hi @garimakaushik22 

We cannot provide an exact answer to this question, as the needed RAM depends directly on the size of the images being used and the architecture of the system where it is run.

So, all we can tell is that the examples from the README using the `research/input.png` image were done in a Linux machine with 32Gb of RAM.

So, could you try using a smaller image? Something that has only a few hundred pixels per side (something like 500x500) and is around 100kb at most.

**Comment by garimakaushik22** [comment] 2019-02-20 16:19
Hi @csala
 Thanks! It worked with smaller image. 
I have 2 questions as mentioned below:
1) It took around 50 sec of time to decode a very small text from a 100Kb of image. Is that fine from performance perspective? 
2) What all image format will it support other than png?

**Comment by csala** [comment] 2019-02-20 16:59
Hi @garimakaushik22 

Yes, that is normal. The process is usually slow, especially when the GPU is not used.

Regarding formats, the input for the encoding can be almost any image format: bmp, png, jpg, gif, etc.

However, the encoding output has to be in a lossless format, like bmp or png. jpg or gif, for example, would not be valid output formats, as the encoder would produce a valid image but the decoder would not be able to extract any message out of it.

**Comment by csala** [comment] 2019-02-20 22:51
Closing the issue, as the original problem seems to be solved. Please feel free to reopen it if there is need for a follow up.

For any further questions unrelated to the `pip install steganogan` command, please open new issues.

**Closed by csala** 2019-02-20 22:51 UTC
Labels: question
